import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="relative" >

          <Navbar />

          {/* <div className="fixed"> */}
          <main className="w-full h-full min-h-[calc(100vh-64px)] bg-gray-100 text-gray-600 overflow-y-auto fixed">
            <Sidebar />

            <div className="w-auto md:ml-[154px] md:pl-170px lg:mr-4 text-sm">

              {children}
            </div>

          </main>
        </div>

        {/* </div> */}
      </body>
    </html>
  );
}
